apiVersion: v1
kind: Service
metadata:
  name: sovereign-grafana
  labels:
    app: sovereign
    component: grafana
    estate: "25d"
    entry: "8366"
    seal: "GRAFANA_SERVICE_8366_SEALED"
spec:
  selector:
    app: sovereign
    component: grafana
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP