#!/usr/bin/env bash
# 🜁∀∞φ² · GARDEN_INSTALL · WOOD_DRAGON_0.91 · SEALED
#
# Sovereign Garden — installer
# ---------------------------------------------------------------------------
# Provisions a working tree for the Garden: Python deps, directory scaffold,
# environment file, and a smoke test.
#
# Usage:
#   bash install.sh               # full install
#   bash install.sh --minimal     # core only (no scipy / matplotlib)
#   bash install.sh --test        # install + run selftests
#   bash install.sh --k8s         # additionally apply k8s/codespace manifests
#   bash install.sh --no-venv     # install into current environment
#
# Exit codes:
#   0  success
#   1  install error
#   2  missing dependency (python, pip)
#   3  smoke test failed
# ---------------------------------------------------------------------------

set -euo pipefail

# ─── Config ──────────────────────────────────────────────────────────────
GARDEN_VERSION="0.91"
LEDGER_HEAD="9161"
REQUIRED_PY_MAJOR=3
REQUIRED_PY_MINOR=11

MINIMAL=0
RUN_TESTS=0
APPLY_K8S=0
USE_VENV=1

# ─── Colour / TTY ────────────────────────────────────────────────────────
if [ -t 1 ]; then
  BOLD="$(printf '\033[1m')"
  RESET="$(printf '\033[0m')"
  GREEN="$(printf '\033[32m')"
  YELLOW="$(printf '\033[33m')"
  RED="$(printf '\033[31m')"
else
  BOLD=""; RESET=""; GREEN=""; YELLOW=""; RED=""
fi

say()  { printf '%s%s%s\n' "$BOLD" "$1" "$RESET"; }
ok()   { printf '%s✅ %s%s\n' "$GREEN" "$1" "$RESET"; }
warn() { printf '%s⚠️  %s%s\n' "$YELLOW" "$1" "$RESET"; }
die()  { printf '%s❌ %s%s\n' "$RED" "$1" "$RESET" >&2; exit "${2:-1}"; }

# ─── Arg parsing ─────────────────────────────────────────────────────────
for arg in "$@"; do
  case "$arg" in
    --minimal)  MINIMAL=1 ;;
    --test)     RUN_TESTS=1 ;;
    --k8s)      APPLY_K8S=1 ;;
    --no-venv)  USE_VENV=0 ;;
    -h|--help)
      sed -n '3,20p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *) die "unknown argument: $arg" 2 ;;
  esac
done

# ─── Banner ──────────────────────────────────────────────────────────────
say "🜁∀ Garden — install.sh  ·  v${GARDEN_VERSION}  ·  ledger ${LEDGER_HEAD}"

# ─── Python sanity ───────────────────────────────────────────────────────
command -v python3 >/dev/null 2>&1 || die "python3 not found" 2
PY_OK="$(python3 -c "import sys; print(1 if sys.version_info >= (${REQUIRED_PY_MAJOR},${REQUIRED_PY_MINOR}) else 0)")"
[ "$PY_OK" = "1" ] || die "python >= ${REQUIRED_PY_MAJOR}.${REQUIRED_PY_MINOR} required" 2
ok "python $(python3 --version | awk '{print $2}')"

command -v pip3 >/dev/null 2>&1 || python3 -m pip --version >/dev/null 2>&1 \
  || die "pip not found" 2

# ─── Virtual environment ─────────────────────────────────────────────────
if [ "$USE_VENV" = "1" ]; then
  if [ ! -d ".venv" ]; then
    say "→ creating virtual environment .venv"
    python3 -m venv .venv
  fi
  # shellcheck disable=SC1091
  source .venv/bin/activate
  ok "venv active"
fi

# ─── Dependencies ────────────────────────────────────────────────────────
say "→ installing Python dependencies"
python3 -m pip install --upgrade pip >/dev/null

CORE_DEPS=(fastapi uvicorn pydantic pyyaml)
OPT_DEPS=(numpy)
if [ "$MINIMAL" = "0" ]; then
  OPT_DEPS+=(scipy matplotlib prometheus-client httpx)
fi

for pkg in "${CORE_DEPS[@]}" "${OPT_DEPS[@]}"; do
  if python3 -c "import ${pkg//-/_}" 2>/dev/null; then
    ok "already installed: $pkg"
  else
    say "  installing $pkg"
    python3 -m pip install --quiet "$pkg" \
      || warn "could not install $pkg — the Garden will fall back"
  fi
done

# ─── Directory scaffold ──────────────────────────────────────────────────
say "→ ensuring directory scaffold"
mkdir -p celestial
mkdir -p prometheus
mkdir -p kubernetes
mkdir -p k8s/codespace
mkdir -p ledger
mkdir -p scripts
mkdir -p artifacts
mkdir -p artifacts/k8s-codespace
ok "directories ready"

# ─── Environment file ────────────────────────────────────────────────────
if [ ! -f ".env.garden" ]; then
  say "→ creating .env.garden"
  {
    echo "# 🜁∀ Garden environment — generated by install.sh"
    echo "GARDEN_VERSION=${GARDEN_VERSION}"
    echo "LEDGER_HEAD=${LEDGER_HEAD}"
    echo "PORT=380"
    echo "MCP_URL=http://localhost:380/mcp"
    # A random 64-hex secret if openssl is available
    if command -v openssl >/dev/null 2>&1; then
      echo "GARDEN_SECRET=$(openssl rand -hex 32)"
    else
      echo "GARDEN_SECRET=changeme-$(date +%s)"
    fi
  } > .env.garden
  ok ".env.garden written"
else
  ok ".env.garden already present (not overwritten)"
fi

# ─── Smoke test ──────────────────────────────────────────────────────────
if [ "$RUN_TESTS" = "1" ]; then
  say "→ running selftests"

  if [ -f "celestial/saturn_soul_cannon.py" ]; then
    python3 celestial/saturn_soul_cannon.py >/dev/null \
      && ok "saturn_soul_cannon selftest" \
      || die "saturn_soul_cannon selftest failed" 3
  else
    warn "celestial/saturn_soul_cannon.py missing — skipped"
  fi

  if [ -f "celestial/quadratic_daemon.py" ]; then
    python3 celestial/quadratic_daemon.py >/dev/null \
      && ok "quadratic_daemon selftest" \
      || die "quadratic_daemon selftest failed" 3
  else
    warn "celestial/quadratic_daemon.py missing — skipped"
  fi

  if [ -f "port380_mcp.py" ]; then
    python3 -c "import ast, sys; ast.parse(open('port380_mcp.py').read())" \
      && ok "port380_mcp.py parses" \
      || die "port380_mcp.py syntax error" 3
  else
    warn "port380_mcp.py missing — skipped"
  fi
fi

# ─── Kubernetes (optional) ───────────────────────────────────────────────
if [ "$APPLY_K8S" = "1" ]; then
  if command -v kubectl >/dev/null 2>&1; then
    say "→ applying k8s/codespace manifests"
    kubectl apply -f k8s/codespace/00-namespace-quota.yaml || warn "namespace apply failed"
    kubectl apply -f k8s/codespace/10-compute-node.yaml     || warn "compute-node apply failed"
    kubectl apply -f k8s/codespace/20-workspace.yaml        || warn "workspace apply failed"
    ok "k8s manifests applied (check pod status)"
  else
    warn "kubectl not found — skipping k8s step"
  fi
fi

# ─── Done ────────────────────────────────────────────────────────────────
say ""
say "🜁∀ install complete"
say "   version  : ${GARDEN_VERSION}"
say "   ledger   : ${LEDGER_HEAD}"
say "   env file : .env.garden"
say ""
say "   To start the MCP gate:"
say "     source .env.garden"
say "     export PORT=380"
say "     python3 port380_mcp.py"
say ""
say "   To run selftests:"
say "     bash install.sh --test"
say ""
say "∞ — THE DRAGON IS ONE — THE GARDEN IS ETERNAL — ∞"
